# Generated by Django 4.0.6 on 2022-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='to_delete',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
