# Generated by Django 4.0.6 on 2022-07-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_name_to_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='to_delete',
        ),
    ]
